---
# file: .../friendly_api/default/config.yaml


security_token: a1234
ansible:
  inventory_path: /etc/ansible/inventory/dynamic
  group_definitions: []
  group_definitions_files: 
    - default/ansible_group_definitions.yaml
